version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mitre-shield-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=mitre-shield
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database-backup:/docker-entrypoint-initdb.d/backup:ro
      - ./scripts/restore-db.sh:/docker-entrypoint-initdb.d/restore-db.sh:ro
    networks:
      - mitre-network

  backend:
    build: ./backend-example
    container_name: mitre-shield-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/mitre-shield
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRE=7d
      - PORT=3000
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3000"
    volumes:
      - ./backend-example/uploads:/app/uploads
    networks:
      - mitre-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: .
    container_name: mitre-shield-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - mitre-network

volumes:
  mongodb_data:

networks:
  mitre-network:
    driver: bridge 